import {
  Globe, Compass, BookOpen, Flame, Mountain, Ship, Castle, Skull, Crown,
  Rocket, Star, Shield, Zap, Brain, Gem, Ghost, Snowflake, Sun, Moon,
  Wind, Waves, Anchor, Eye, Heart, Target, Wand2, Fish, Bug,
  Flower, TreePine, Cloud, Sunrise, Eclipse, Hexagon, Diamond, Atom,
  type LucideIcon,
} from 'lucide-react';

/** 内置图标列表（30个） */
export const WORLD_ICONS: Array<{ name: string; icon: LucideIcon }> = [
  { name: 'Globe', icon: Globe },
  { name: 'Compass', icon: Compass },
  { name: 'BookOpen', icon: BookOpen },
  { name: 'Flame', icon: Flame },
  { name: 'Mountain', icon: Mountain },
  { name: 'Ship', icon: Ship },
  { name: 'Castle', icon: Castle },
  { name: 'Skull', icon: Skull },
  { name: 'Crown', icon: Crown },
  { name: 'Rocket', icon: Rocket },
  { name: 'Star', icon: Star },
  { name: 'Shield', icon: Shield },
  { name: 'Zap', icon: Zap },
  { name: 'Brain', icon: Brain },
  { name: 'Gem', icon: Gem },
  { name: 'Ghost', icon: Ghost },
  { name: 'Snowflake', icon: Snowflake },
  { name: 'Sun', icon: Sun },
  { name: 'Moon', icon: Moon },
  { name: 'Wind', icon: Wind },
  { name: 'Waves', icon: Waves },
  { name: 'Anchor', icon: Anchor },
  { name: 'Eye', icon: Eye },
  { name: 'Heart', icon: Heart },
  { name: 'Target', icon: Target },
  { name: 'Wand2', icon: Wand2 },
  { name: 'Fish', icon: Fish },
  { name: 'Flower', icon: Flower },
  { name: 'TreePine', icon: TreePine },
  { name: 'Cloud', icon: Cloud },
];
